### ISSUE TITLE
View Ingredients List Bug

### ISSUE THREAD

**Issue by Gnarlywhale** [earthiverse/Food#13]
The View Ingredients List branch has been pushed but there is a bug I have yet to identify, resulting in no ingredients being listed :octopus:. I believe the error is probably coming from the custom adapter (FoodListAdapter.java). For reference, I followed this guide rather closely:
http://www.framentos.com/en/android-tutorial/2012/07/16/listview-in-android-using-custom-listadapter-and-viewcache/

**Comment by earthiverse** [comment]
Rewrote code, works.
