### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by Gnarlywhale** [earthiverse/Food#19]
The UML has been pushed in the "UML" branch and the wiki has been updated, please review for accuracy/validity.
I am also unsure as what is meant in the submission requirements by "Include notes on the use of design patterns among the classes," since our code really only reflects basic OOP concepts (no singletons or any other majour design pattern that I'm aware of). If anyone has a suggestion, please feel free to give it to me, otherwise I'm going to try to ask the prof about it tomorrow.

**Comment by earthiverse** [comment]
Recipe can have more than one photo.
The photo class doesn't have a Bitmap variable to store the photo data.
The user class doesn't have a username variable.
Recipe doesn't have an author.
The database doesn't have a query recipe function.
Cache doesn't have a collection of ingredients to represent pantry.

Is it possible to add a comment for the aggregates on Cache? (Recipe Book & Pantry)

Recipe should have remove\* methods for steps, ingredients, photos 

We might need a share class of some sort, I don't know at this point in time, though. We should discuss this.

**Comment by solinas** [comment]
Also, I think we need to get rid of the variable instances that are found outside the individual classes, next to the lines connecting thee classes. Those seem to just be local variables and should not be included in UML
