### ISSUE TITLE
Requirements Specifications

### ISSUE THREAD

**Issue by Gnarlywhale** [earthiverse/Food#2]
#### Step 1

Finish Use Cases
UC1,2,3,4,6 - @gongal 
UC5,7,8,11 - @earthiverse
UC9,10,12 - @Gnarlywhale and @solinas10
#### Step 2

Re-organize use case for hierarchy (What use cases are per-requisites for others? What use cases should be grouped together?)
Consider renaming them in to groups, too. (i.e. 1.1 - sign up, 1.2 - login, 2.1 - create recipe, 2.2 - edit recipe, 2.3 - share recipe, etc...)
#### Step 3

Re-visit UML diagram, see if anything is missed. See also if anything is included that doesn't have a place in the overall plan.

**Comment by earthiverse** [comment]
Use http://www.agilemodeling.com/artifacts/systemUseCase.htm as a guideline, please.
The alternate flows are a good idea.

**Comment by earthiverse** [comment]
1 - User Login
2 - User Signup
3 - Add Ingredient
4 - Edit Ingredient
5 - Search Recipes
6 - Record Recipe
6a. Add Ingredient to Recipe
6b. Add Step to Recipe
7 - Share Recipe [Email]
8 - Post Recipe [To Server]
9 - Take Photo
10 - View Ingredients
11 - View Recipes
12 - Download Recipe

Another website for guidelines: http://www.gatherspace.com/static/use_case_example.html#6

**Comment by earthiverse** [comment]
http://discuss.joelonsoftware.com/default.asp?design.4.7340.13
UC1 should not be included.

**Comment by Gnarlywhale** [comment]
UC9, 10 done, feel free to check them... UC10 seems bare or lazily done or something.

**Comment by earthiverse** [comment]
Chris ( @solinas10 ), or whoever, can you separate the edit/add ingredients in to two different use cases, and add an edit recipe use case to help satisfy US10 ("As a user, I can upload photos for other recipes I did not make, but were downloaded.").
This will also require re-numbering the use cases (Please put the two ingredient use cases and the two recipe use cases next to each other).

**Comment by solinas** [comment]
Use cases for edit/add ingredients are now separate. Edit recipe is now added as UC 7. Use cases seem to be in proper order. Thanks @earthiverse for making it easy.

**Comment by earthiverse** [comment]
Riley ( @Gnarlywhale ) is responsible reviewing the UML class diagram now. After that's finished, someone fill in the core functionality we decided to implement (I'm hoping Riley has this written down) on the [Release Plan](https://github.com/CMPUT301W13T04/Food/wiki/Release-Plan) page.

**Comment by solinas** [comment]
We still need the User login and sign up use cases from Amshu ( @gongal )

**Comment by earthiverse** [comment]
See a couple comments up:

```
http://discuss.joelonsoftware.com/default.asp?design.4.7340.13
UC1 should not be included.
```

It's a by-product of the use cases, not a use case in itself.

**Comment by gongal** [comment]
Looks Great Guys! Well done!
Cheers
