### ISSUE TITLE
Recipe Creation 

### ISSUE THREAD

**Issue by earthiverse** [earthiverse/Food#6]
Wouldn't it make more sense to compile the ingredients needed for the entire recipe from the ingredients needed in each step, instead of having a list of them at the beginning of the recipe creation?

**Comment by solinas** [comment]
I don't think so. Most recipes are formatted with ingredients first, and then directions. Plus some ingredients could be used in multiple steps. I think it's easier for a user to just enter all the ingredients you need, and then explain the steps.

**Comment by earthiverse** [comment]
When they are presented after completion, the ingredients are first, and they still will be. But when you are creating a recipe, why would you need to have a list of all of the ingredients before you add the steps?
If we require the ingredients in each step as well as at the beginning, are we not duplicating the work for the user, as well as possibly creating errors in the recipe when an ingredient could be absent from the steps, but still in the main ingredient list? Or a step using an ingredient that isn't in the ingredient list at the beginning?
We should have separate ingredient lists for each step in the creation, and combine them when viewing the recipe.

**Comment by earthiverse** [comment]
We can also use the same concepts for the time to make a recipe, if we let the users define the time for each step.

Also, we could allow 'zero' time, and if the sum at the end of the recipe is 'zero', we could say something quirky like 'No time at all!'. FUN!

**Comment by Gnarlywhale** [comment]
We could set it up so that the users enter all the ingredients once, then during each step, simply have a check list of available ingredients from which to include in the step.

In any case, Chris' description is accurate to how most users will be used to recipes, see: http://allrecipes.com/recipe/best-ever-banana-bread/detail.aspx

**Comment by earthiverse** [comment]
It's settled, then.
We're going with ingredients as the first step to recipe creation, instead of as sub-steps in the each step of the recipe directions.
