### ISSUE TITLE
Updating the cache

### ISSUE THREAD

**Issue by solinas** [earthiverse/Food#9]
Here's how I've setup the cache to be updated.

Cache cache = new Cache();
cache.load();
// now apply any update operations using getters and setters
cache.save();          // save if you want any changes to persist

This allows us to avoid using a singleton, and also avoid using unnecessary bundles / intent extras.

Note: we will still have to use intents in any activity that requires data from the parent acivity.

**Comment by solinas** [comment]
The other option would be for me to call load and save inside the getters and setters

**Comment by earthiverse** [comment]
I think the first way is good.
Is it okay to have cache.load() moved inside the constructor?

So, you only need to do

```
Cache cache = new Cache();
/* Make Some Changes To Cache */
cache.save();
```

**Comment by solinas** [comment]
Yes, good idea.

**Comment by earthiverse** [comment]
We couldn't do the load in the constructor, because when we use GSON to convert the Cache, it tried to include the context in the file.
Also, we had trouble saving to two files, so we decided to throw everything in one file.

The cache needs testing now.

The cache is accessed as such:

```
Cache cache = new Cache();
cache.load(__Context (Usually "this")__);
/* Functions to and from cache */
cache.save(__Context (Usually "this")__);
```

**Comment by solinas** [comment]
Cache is complete and fully functional.
